"""initial_schema

Revision ID: 2705b51e295d
Revises: 
Create Date: 2026-07-16 11:23:50.069623
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '2705b51e295d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='lifecyclestatus', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants'))
    )
    op.create_index(op.f('ix_plants_name'), 'plants', ['name'], unique=False)
    op.create_table('workers',
    sa.Column('worker_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('designation', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='lifecyclestatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers'))
    )
    op.create_index(op.f('ix_workers_worker_code'), 'workers', ['worker_code'], unique=True)
    op.create_table('compliance_reports',
    sa.Column('plant_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('framework', sa.Enum('OSHA', 'ISO_45001', 'FACTORY_ACT', 'OISD', name='complianceframework', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_compliance_reports_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_reports'))
    )
    op.create_index(op.f('ix_compliance_reports_generated_at'), 'compliance_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_compliance_reports_plant_id'), 'compliance_reports', ['plant_id'], unique=False)
    op.create_table('documents',
    sa.Column('plant_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_documents_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_plant_id'), 'documents', ['plant_id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PLANT_MANAGER', 'SAFETY_OFFICER', 'MAINTENANCE', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('plant_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='lifecyclestatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_users_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_plant_id'), 'users', ['plant_id'], unique=False)
    op.create_table('zones',
    sa.Column('plant_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('zone_name', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severitylevel', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_zones_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    op.create_index(op.f('ix_zones_plant_id'), 'zones', ['plant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_history'))
    )
    op.create_index(op.f('ix_chat_history_timestamp'), 'chat_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('equipment',
    sa.Column('plant_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('zone_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'OFFLINE', 'MAINTENANCE', name='equipmentstatus', native_enum=False), nullable=False),
    sa.Column('last_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('source_dataset', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_equipment_plant_id_plants')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_equipment_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('external_id', name=op.f('uq_equipment_external_id'))
    )
    op.create_index(op.f('ix_equipment_plant_id'), 'equipment', ['plant_id'], unique=False)
    op.create_index(op.f('ix_equipment_zone_id'), 'equipment', ['zone_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel', native_enum=False), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('zone_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('SAFE', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severitylevel', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('expected_consequence', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'MITIGATED', 'CLOSED', name='riskstatus', native_enum=False), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('affected_workers', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_risk_events_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_risk_score'), 'risk_events', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_events_zone_id'), 'risk_events', ['zone_id'], unique=False)
    op.create_table('worker_locations',
    sa.Column('worker_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('zone_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_locations_worker_id_workers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_worker_locations_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_locations'))
    )
    op.create_index(op.f('ix_worker_locations_timestamp'), 'worker_locations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_locations_worker_id'), 'worker_locations', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_locations_zone_id'), 'worker_locations', ['zone_id'], unique=False)
    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('SAFE', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severitylevel', native_enum=False), nullable=False),
    sa.Column('zone_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('equipment_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('worker_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('incident_type', sa.Enum('SAFETY_INCIDENT', 'NEAR_MISS', 'EQUIPMENT_FAILURE', 'FIRE', 'GAS_LEAK', 'CHEMICAL_EXPOSURE', 'WORKER_COLLAPSE', name='incidenttype', native_enum=False), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CLOSED', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('source_dataset', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_incidents_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_incidents_worker_id_workers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_incidents_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_equipment_id'), 'incidents', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_incidents_reported_at'), 'incidents', ['reported_at'], unique=False)
    op.create_index(op.f('ix_incidents_title'), 'incidents', ['title'], unique=False)
    op.create_index(op.f('ix_incidents_worker_id'), 'incidents', ['worker_id'], unique=False)
    op.create_index(op.f('ix_incidents_zone_id'), 'incidents', ['zone_id'], unique=False)
    op.create_table('maintenance',
    sa.Column('equipment_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'EMERGENCY', name='maintenancetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'RUNNING', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='maintenancestatus', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_maintenance_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance'))
    )
    op.create_index(op.f('ix_maintenance_equipment_id'), 'maintenance', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_scheduled_date'), 'maintenance', ['scheduled_date'], unique=False)
    op.create_table('permits',
    sa.Column('permit_number', sa.String(length=64), nullable=False),
    sa.Column('permit_type', sa.Enum('HOT_WORK', 'CONFINED_SPACE', 'ELECTRICAL', 'WORKING_AT_HEIGHT', 'COLD_WORK', 'GENERAL', name='permittype', native_enum=False), nullable=False),
    sa.Column('worker_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('zone_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('equipment_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'APPROVED', 'SUSPENDED', 'EXPIRED', 'CLOSED', name='permitstatus', native_enum=False), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_permits_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_permits_worker_id_workers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_permits_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permits'))
    )
    op.create_index(op.f('ix_permits_equipment_id'), 'permits', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_permits_permit_number'), 'permits', ['permit_number'], unique=True)
    op.create_index(op.f('ix_permits_worker_id'), 'permits', ['worker_id'], unique=False)
    op.create_index(op.f('ix_permits_zone_id'), 'permits', ['zone_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('risk_event_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'DISMISSED', name='recommendationstatus', native_enum=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], name=op.f('fk_recommendations_risk_event_id_risk_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_risk_event_id'), 'recommendations', ['risk_event_id'], unique=False)
    op.create_table('sensors',
    sa.Column('equipment_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('zone_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('sensor_name', sa.String(length=255), nullable=False),
    sa.Column('sensor_type', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'OFFLINE', 'FAULTY', 'MAINTENANCE', name='sensorstatus', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_sensors_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_sensors_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('external_id', name=op.f('uq_sensors_external_id'))
    )
    op.create_index(op.f('ix_sensors_equipment_id'), 'sensors', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_type'), 'sensors', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensors_zone_id'), 'sensors', ['zone_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('sensor_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_sensor_readings_sensor_id_sensors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_readings'))
    )
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensors_zone_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_sensor_type'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_equipment_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_recommendations_risk_event_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_permits_zone_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_worker_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_permit_number'), table_name='permits')
    op.drop_index(op.f('ix_permits_equipment_id'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_maintenance_scheduled_date'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_equipment_id'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('ix_incidents_zone_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_worker_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_title'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reported_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_equipment_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_worker_locations_zone_id'), table_name='worker_locations')
    op.drop_index(op.f('ix_worker_locations_worker_id'), table_name='worker_locations')
    op.drop_index(op.f('ix_worker_locations_timestamp'), table_name='worker_locations')
    op.drop_table('worker_locations')
    op.drop_index(op.f('ix_risk_events_zone_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_risk_score'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_equipment_zone_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_plant_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_timestamp'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_zones_plant_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_plant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_plant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_compliance_reports_plant_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_generated_at'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_workers_worker_code'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_plants_name'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
